version: "3"

includes:
  admin:
    taskfile: ./apps/admin/Taskfile.yaml
    dir: ./apps/admin
  gateway:
    taskfile: ./apps/gateway/Taskfile.yaml
    dir: ./apps/gateway
  tgbot:
    taskfile: ./apps/tg-bot/Taskfile.yaml
    dir: ./apps/tg-bot

tasks:
  build-libs:
    cmds:
      - pnpm run build:libs
  migrations:
    cmds:
      - pnpm run --filter=@shgpu-table/typeorm setup
  prepare:
    run: once
    cmds:
      - task: build-libs
      - task: migrations
  admin-dev:
    deps: [prepare]
    cmds:
      - task: admin:dev
  gateway-dev:
    deps: [prepare]
    cmds:
      - task: gateway:dev
  tgbot-dev:
    deps: [prepare]
    cmds:
      - task: tgbot:dev
  node-dev:
    deps: [prepare]
    cmds:
      - pnpm run dev
  dev:
    deps: [admin-dev, node-dev, gateway-dev]