version: '3'

includes:
  admin:
    taskfile: ./apps/admin/Taskfile.yaml
    dir: ./apps/admin

tasks:
  build-libs:
    cmds:
      - npm run build:libs
      # - task migrations
  # migrations:
    # cmds:
      # - npm run --workspace=typeorm setup
  prepare:
    run: once
    cmds:
      - task: build-libs
  admin-dev:
    deps: [prepare]
    cmds:
      - task: admin:dev
  gateway-dev:
    deps: [prepare]
    cmds:
      - task: gateway:dev
  node-dev:
    deps: [prepare]
    cmds:
      - npm run dev
  dev:
    deps: [admin-dev, node-dev]
  

