version: '3'

includes:
  admin:
    taskfile: ./apps/admin/Taskfile.yaml
    dir: ./apps/admin
  parser:
    taskfile: ./apps/parser/Taskfile.yaml
    dir: ./apps.parser

tasks:
  build-libs:
    cmds:
      - npm run build:libs
  prepare:
    run: once
    cmds:
      - task: build-libs
  admin-dev:
    deps: [prepare]
    cmds:
      - task: admin:dev
  gateway-dev:
    deps: [prepare]
    cmds:
      - task: gateway:dev
  parser-dev:
    deps: [prepare]
    cmds:
      - task: parser:dev
  node-dev:
    deps: [prepare]
    cmds:
      - npm run dev
  dev:
    deps: [admin-dev, node-dev]
  

