import Head from "next/head";
import { Inter } from "@next/font/google";
import { Flex, SelectItem, useMantineTheme } from "@mantine/core";
import AddAdvertising from "@/components/addadvertising";
import { PublicFaculty } from "../../../libs/shared/src";
import { ACCESS_TOKEN_KEY, fetcher } from "@/services/api/fetchWrappers";
import { GetServerSideProps, GetStaticProps } from "next";
import { AboutAdmin, authManager } from "@/services/api/auth";
import React from "react";
import Advertisings from "@/components/advertisings";
import { $axios, $serverAxios } from "@/services/api/axios/axios";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  faculties: SelectItem[];
};

const Home = ({ faculties }: Props) => {
  const theme = useMantineTheme();
  const { data, isLoading } = authManager.useGetProfile();
  if (!data && !isLoading) {
    window.location.replace("/login");
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>
        <AddAdvertising faculties={faculties} />
        <Advertisings />
      </Flex>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  localStorage.getItem(ACCESS_TOKEN_KEY);
  const response = await $serverAxios<{ faculties: PublicFaculty[] }>({
    method: "get",
    url: "/v1/faculties",
  });
  if (!response)
    return {
      props: {
        faculties: [],
      },
    };
  const { faculties } = response?.data;
  const preparedFaculties: SelectItem[] = [];
  faculties.forEach((faculty: PublicFaculty) => {
    preparedFaculties.push({
      value: `${faculty.id}`,
      label: faculty.name,
    });
  });
  return {
    props: {
      faculties: preparedFaculties,
    },
  };
};

export default Home;
