import Head from "next/head";
import { Inter } from "@next/font/google";
import { SelectItem, useMantineTheme } from "@mantine/core";
import Advertising from "@/components/advertising";
import { PublicFaculty } from "../../../libs/shared/src";
import { fetcher } from "@/services/api/fetchWrappers";
import { GetStaticProps } from "next";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  faculties: SelectItem[];
};

const Home = ({ faculties }: Props) => {
  const theme = useMantineTheme();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {theme.colorScheme}
      <Advertising faculties={faculties} />
    </div>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const { faculties } = await fetcher<{ faculties: PublicFaculty[] }>(
    "http://localhost:3002/v1/faculties"
  );
  const preparedFaculties: SelectItem[] = [];
  faculties.forEach((faculty: PublicFaculty) => {
    preparedFaculties.push({
      value: `${faculty.id}`,
      label: faculty.name,
    });
  });
  console.log(preparedFaculties);
  return {
    props: {
      faculties: preparedFaculties,
    },
  };
};

export default Home;
