import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { useMantineTheme } from "@mantine/core";
import { NextPage } from "next";
import withAuth from "@/components/hoc/withAuth";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = () => {
  const theme = useMantineTheme();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {theme.colorScheme}
    </div>
  );
};

export default withAuth(Home);
